@uri = http://localhost:3000/api/front/common/
###
GET {{uri}}page_articles/page/about
###
DELETE  {{uri}}upload/del/card_img/d21f5d8a24a06216fa2f96cc8a5f737e
###
GET {{uri}}articles/list/1
###
GET {{uri}}articles/search/购买/list/1
###
PUT {{uri}}editArticle/5d73cb4607f5a62118c8702e
Content-Type: application/json

{
  "title": "ccc",
  "content": "cccccc"
}
###
DELETE {{uri}}delArticle/5d73cb4607f5a62118c8702e
